# Generated by Django 4.1.4 on 2022-12-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tree_id',
        ),
    ]
