# Generated by Django 4.1.4 on 2022-12-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_product_level_remove_product_lft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='level',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='tree_id',
        ),
    ]
